#!/usr/bin/env python3
"""Generate an original deterministic bunny-like ASCII PCD demo asset.

This is not the Stanford Bunny. It is composed from sampled ellipsoid surfaces so the
archive has no external model/download dependency.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass(frozen=True, slots=True)
class Part:
    center: tuple[float, float, float]
    radii: tuple[float, float, float]
    count: int
    color: tuple[int, int, int]
    rotation_deg_xyz: tuple[float, float, float] = (0.0, 0.0, 0.0)


def rotation_matrix(degrees_xyz: tuple[float, float, float]) -> np.ndarray:
    x, y, z = np.deg2rad(degrees_xyz)
    rx = np.array([[1, 0, 0], [0, np.cos(x), -np.sin(x)], [0, np.sin(x), np.cos(x)]])
    ry = np.array([[np.cos(y), 0, np.sin(y)], [0, 1, 0], [-np.sin(y), 0, np.cos(y)]])
    rz = np.array([[np.cos(z), -np.sin(z), 0], [np.sin(z), np.cos(z), 0], [0, 0, 1]])
    return rz @ ry @ rx


def sample_part(part: Part, rng: np.random.Generator) -> tuple[np.ndarray, np.ndarray]:
    directions = rng.normal(size=(part.count, 3))
    directions /= np.linalg.norm(directions, axis=1, keepdims=True)
    # Slightly irregular surface makes the point cloud read as scanned geometry.
    radial_jitter = rng.normal(1.0, 0.018, size=(part.count, 1))
    points = directions * np.asarray(part.radii) * radial_jitter
    points = points @ rotation_matrix(part.rotation_deg_xyz).T
    points += np.asarray(part.center)
    colors = np.tile(np.asarray(part.color, dtype=np.uint8), (part.count, 1))
    return points.astype(np.float32), colors


def generate(seed: int = 20260817) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    fur = (204, 216, 232)
    shadow = (160, 180, 207)
    pink = (232, 157, 180)
    parts = (
        Part((0.00, -0.08, 0.00), (0.52, 0.41, 0.38), 4800, fur),
        Part((0.00, 0.42, 0.11), (0.31, 0.30, 0.29), 2800, fur),
        Part((-0.14, 0.82, 0.04), (0.095, 0.36, 0.085), 1200, shadow, (0, 0, -8)),
        Part((0.14, 0.82, 0.04), (0.095, 0.36, 0.085), 1200, shadow, (0, 0, 8)),
        Part((-0.14, 0.84, 0.115), (0.040, 0.28, 0.025), 420, pink, (0, 0, -8)),
        Part((0.14, 0.84, 0.115), (0.040, 0.28, 0.025), 420, pink, (0, 0, 8)),
        Part((-0.31, -0.35, 0.16), (0.27, 0.14, 0.23), 850, shadow, (0, -10, 4)),
        Part((0.31, -0.35, 0.16), (0.27, 0.14, 0.23), 850, shadow, (0, 10, -4)),
        Part((0.00, -0.02, -0.38), (0.19, 0.19, 0.19), 650, fur),
        Part((0.00, 0.34, 0.39), (0.070, 0.050, 0.045), 260, pink),
        Part((-0.105, 0.49, 0.355), (0.035, 0.047, 0.025), 180, (42, 54, 73)),
        Part((0.105, 0.49, 0.355), (0.035, 0.047, 0.025), 180, (42, 54, 73)),
    )
    point_sets: list[np.ndarray] = []
    color_sets: list[np.ndarray] = []
    for part in parts:
        points, colors = sample_part(part, rng)
        point_sets.append(points)
        color_sets.append(colors)
    return np.vstack(point_sets), np.vstack(color_sets)


def write_pcd(path: Path, points: np.ndarray, colors: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    count = points.shape[0]
    header = f"""# .PCD v0.7 - Point Cloud Data file format
# Original synthetic bunny-like point cloud generated by scripts/generate_bunny.py
VERSION 0.7
FIELDS x y z r g b
SIZE 4 4 4 1 1 1
TYPE F F F U U U
COUNT 1 1 1 1 1 1
WIDTH {count}
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS {count}
DATA ascii
"""
    with path.open("w", encoding="ascii") as handle:
        handle.write(header)
        for point, color in zip(points, colors, strict=True):
            handle.write(
                f"{point[0]:.7f} {point[1]:.7f} {point[2]:.7f} "
                f"{int(color[0])} {int(color[1])} {int(color[2])}\n"
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/headcoupled_display/static/assets/bunny.pcd"),
    )
    parser.add_argument("--seed", type=int, default=20260817)
    args = parser.parse_args()
    points, colors = generate(args.seed)
    write_pcd(args.output, points, colors)
    print(f"wrote {len(points)} points to {args.output}")


if __name__ == "__main__":
    main()
